name: Super-Linter
on: push
jobs: 
  superlint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name:
      uses: actions/checkout@v4
      - name: Run Super-Linter
      uses: github/super-linter@v4
